services:
  # Frontend Service
  - type: web
    name: charism-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && node server.js
    plan: free
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_ENV
        value: production

  # Backend Service  
  - type: web
    name: charism-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000